SELECT * FROM customer;

--Q1. what is the total revenue generated by male vs female customers?
SELECT
	gender, 
	SUM(purchase_amount) AS revenue_generated
FROM customer
GROUP BY gender;

--Q2. which customer used a discount but still spent more than the average purchase amount?
SELECT 
	customer_id,
	age,
	gender,
	purchase_amount
FROM customer
WHERE discount_applied= 'Yes' AND 
	  purchase_amount> (SELECT AVG(purchase_amount) FROM customer);

--Q3 which are the top 5 products with the highest average review rating
SELECT
	item_purchased,
	ROUND(AVG(review_rating::numeric),2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4 compare the average purchase amount between standard and express shipping 
SELECT 
	shipping_type,
	ROUND(AVG(purchase_amount::numeric),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

/*Q5 do subscribed customers pay more? compare average spend and total revenue between subscribers and
non-subscribers*/
SELECT
	subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount::numeric),2) AS average_spent,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spent DESC;

--Q6 which 5 products have the highest percentage of purchases with discounts applied
SELECT
	item_purchased,
	ROUND(100 * SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7 segment customers into new, returning and loyal based on their total number of previous
--purchases and show the count of each segment.
WITH segment AS(
SELECT
	customer_id,
	age,
	gender,
	previous_purchases,
	CASE
		WHEN previous_purchases<2 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT 
	customer_segment,
	COUNT(customer_segment) AS number_of_customers
FROM segment
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- Q8 what are the top 3 most purchased products within each category?
WITH purchased_rank AS(
SELECT 
	category,
	item_purchased,
	COUNT(*) AS total_order,
	ROW_NUMBER()OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS purchase_rank
FROM customer
GROUP BY category, item_purchased
ORDER BY category
)
SELECT 
	*
FROM purchased_rank
WHERE purchase_rank<=3;

--Q9 are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	subscription_status,
	COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;

--Q10 what is the revenue contribution of each age group
SELECT 
	age_group,
	sum(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;